{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 0,
   "metadata": {
    "application/vnd.databricks.v1+cell": {
     "cellMetadata": {},
     "inputWidgets": {},
     "nuid": "61dc310f-4dbb-4503-8384-41f2c262b478",
     "showTitle": false,
     "tableResultSettingsMap": {},
     "title": ""
    }
   },
   "outputs": [],
   "source": [
    "-- ============================================================\n",
    "-- Users & Watchlists\n",
    "-- ============================================================\n",
    "\n",
    "CREATE TABLE users (\n",
    "    user_id SERIAL PRIMARY KEY,\n",
    "    email TEXT NOT NULL UNIQUE,\n",
    "    display_name TEXT,\n",
    "    created_at TIMESTAMPTZ NOT NULL DEFAULT now()\n",
    ");\n",
    "\n",
    "-- One watchlist per user, enforced via UNIQUE on user_id.\n",
    "CREATE TABLE watchlists (\n",
    "    watchlist_id SERIAL PRIMARY KEY,\n",
    "    user_id INTEGER NOT NULL UNIQUE REFERENCES users(user_id),\n",
    "    created_at TIMESTAMPTZ NOT NULL DEFAULT now()\n",
    ");\n",
    "\n",
    "CREATE TABLE watchlist_tickers (\n",
    "    watchlist_id INTEGER NOT NULL REFERENCES watchlists(watchlist_id),\n",
    "    symbol TEXT NOT NULL,\n",
    "    added_at TIMESTAMPTZ NOT NULL DEFAULT now(),\n",
    "    PRIMARY KEY (watchlist_id, symbol)\n",
    ");\n",
    "\n",
    "-- ============================================================\n",
    "-- Market data\n",
    "-- ============================================================\n",
    "\n",
    "CREATE TABLE companies (\n",
    "    symbol TEXT PRIMARY KEY,\n",
    "    name TEXT,\n",
    "    sector TEXT,\n",
    "    industry TEXT,\n",
    "    description TEXT,          -- company profile text, embedded for semantic retrieval\n",
    "    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()\n",
    ");\n",
    "\n",
    "-- Composite PK: one row per symbol per timestamp, since this is time-series data.\n",
    "CREATE TABLE price_snapshots (\n",
    "    symbol TEXT NOT NULL REFERENCES companies(symbol),\n",
    "    snapshot_time TIMESTAMPTZ NOT NULL,\n",
    "    price NUMERIC NOT NULL,\n",
    "    volume BIGINT,\n",
    "    source TEXT NOT NULL DEFAULT 'massive',\n",
    "    daily_return_pct NUMERIC,\n",
    "    moving_avg_7d NUMERIC,\n",
    "    PRIMARY KEY (symbol, snapshot_time)\n",
    ");\n",
    "\n",
    "CREATE INDEX IF NOT EXISTS idx_price_snapshots_symbol_time\n",
    "    ON price_snapshots (symbol, snapshot_time DESC);\n",
    "\n",
    "-- ============================================================\n",
    "-- Unstructured text sources (embedded for RAG)\n",
    "-- ============================================================\n",
    "\n",
    "CREATE TABLE news_articles (\n",
    "    id TEXT PRIMARY KEY,           -- external article id from Massive\n",
    "    symbol TEXT REFERENCES companies(symbol),\n",
    "    title TEXT NOT NULL,\n",
    "    description TEXT,              -- narrative text to embed\n",
    "    source TEXT,\n",
    "    published_at TIMESTAMPTZ,\n",
    "    url TEXT,\n",
    "    payload JSONB NOT NULL,\n",
    "    synced_at TIMESTAMPTZ NOT NULL DEFAULT now()\n",
    ");\n",
    "\n",
    "CREATE INDEX IF NOT EXISTS idx_news_articles_symbol ON news_articles (symbol);\n",
    "\n",
    "-- Filings excerpts and earnings-call summaries. Kept separate from\n",
    "-- news_articles since they come from different sources and have a\n",
    "-- different natural shape (long-form document text, not a short article).\n",
    "CREATE TABLE company_documents (\n",
    "    id TEXT PRIMARY KEY,\n",
    "    symbol TEXT NOT NULL REFERENCES companies(symbol),\n",
    "    document_type TEXT NOT NULL,   -- 'filing_excerpt' or 'earnings_summary'\n",
    "    title TEXT,\n",
    "    document_text TEXT NOT NULL,   -- long-form narrative text, embedded for RAG\n",
    "    source_url TEXT,\n",
    "    published_at TIMESTAMPTZ,\n",
    "    payload JSONB,\n",
    "    synced_at TIMESTAMPTZ NOT NULL DEFAULT now()\n",
    ");\n",
    "\n",
    "CREATE INDEX IF NOT EXISTS idx_company_documents_symbol\n",
    "    ON company_documents (symbol);\n",
    "\n",
    "CREATE INDEX IF NOT EXISTS idx_company_documents_type\n",
    "    ON company_documents (document_type);\n",
    "\n",
    "-- ============================================================\n",
    "-- User-generated content (agent write actions land here)\n",
    "-- ============================================================\n",
    "\n",
    "CREATE TABLE research_notes (\n",
    "    note_id SERIAL PRIMARY KEY,\n",
    "    user_id INTEGER NOT NULL REFERENCES users(user_id),\n",
    "    symbol TEXT REFERENCES companies(symbol),\n",
    "    note_text TEXT NOT NULL,\n",
    "    created_at TIMESTAMPTZ NOT NULL DEFAULT now()\n",
    ");\n",
    "\n",
    "CREATE TABLE analysis_reports (\n",
    "    report_id SERIAL PRIMARY KEY,\n",
    "    user_id INTEGER NOT NULL REFERENCES users(user_id),\n",
    "    symbols TEXT[] NOT NULL,       -- array, since a report may compare multiple tickers\n",
    "    report_type TEXT NOT NULL DEFAULT 'summary',  -- e.g. 'summary', 'comparison', 'thesis_check'\n",
    "    report_text TEXT NOT NULL,\n",
    "    created_at TIMESTAMPTZ NOT NULL DEFAULT now()\n",
    ");\n",
    "\n",
    "-- ============================================================\n",
    "-- Embeddings (not one of the 8 named tables, but required by\n",
    "-- the \"context engineering\" section - mirrors weather_embeddings\n",
    "-- from the Day 2 homework)\n",
    "-- ============================================================\n",
    "\n",
    "CREATE TABLE document_embeddings (\n",
    "    id TEXT PRIMARY KEY,\n",
    "    source_type TEXT NOT NULL,     -- 'company_profile', 'news_article', 'filing_excerpt', 'earnings_summary'\n",
    "    source_id TEXT NOT NULL,       -- e.g. companies.symbol or news_articles.id\n",
    "    chunk_index INTEGER NOT NULL,\n",
    "    chunk_text TEXT NOT NULL,\n",
    "    embedding VECTOR(384),\n",
    "    model_name TEXT NOT NULL,\n",
    "    created_at TIMESTAMPTZ NOT NULL DEFAULT now()\n",
    ");\n",
    "\n",
    "CREATE INDEX IF NOT EXISTS idx_document_embeddings_source\n",
    "    ON document_embeddings (source_type, source_id);\n",
    "\n",
    "CREATE INDEX IF NOT EXISTS idx_document_embeddings_hnsw\n",
    "    ON document_embeddings USING hnsw (embedding vector_cosine_ops);"
   ]
  }
 ],
 "metadata": {
  "application/vnd.databricks.v1+notebook": {
   "computePreferences": null,
   "dashboards": [],
   "environmentMetadata": null,
   "inputWidgetPreferences": null,
   "language": "sql",
   "notebookMetadata": {
    "pythonIndentUnit": 4,
    "sqlQueryOptions": {
     "applyAutoLimit": true,
     "catalog": "workspace",
     "schema": "default"
    }
   },
   "notebookName": "table-schema-stock-market.sql.dbquery.ipynb",
   "widgets": {}
  },
  "language_info": {
   "name": "sql"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 0
}